project:
  type: website
  title: "Sri Lanka Dengue Atlas"
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - spatial.qmd
      - time.qmd
      - seasonal.qmd
      - summary.qmd
      - population.qmd
      - about.qmd
    right: 
      - icon: github
        href: https://github.com/thiyangt/DengueAtlas
      - icon: twitter
        href: https://twitter.com/thiyangt

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    number-sections: true
    fig-caption: true
    toc: true

editor: visual

